### POST a tag
POST http://localhost:4000/tags
Content-Type: application/json

{
    "tag_name": "paysage"
}

### PUT a tag
PUT http://localhost:4000/tags/5
Content-Type: application/json

{
    "tag_name": "cat"
}

### GET all tags
GET http://localhost:4000/tags

### GET tag by ID
GET http://localhost:4000/tags/3

# ### DELETE tag by ID
# DELETE http://localhost:4000/tag/7